name: CI
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  package:
    name: deploy artifact
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: publish to git
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: 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

